### ISSUE TITLE
Idea: Use lightweight types for scale and position vectors, colors, and quaternions

### ISSUE THREAD

**Issue by TedDriggs** [shockham/caper#25]
Full disclosure: I've never tried to develop a game, and probably never will get the chance. This idea is based purely on my reading of the examples and my experience writing Rust APIs.

Right now, the crate is using type aliases over tuples to represent vectors. This works, but it precludes creating `Default` impls for these types (or other trait impls), and it means there's no type safety preventing me from accidentally using a `Quaternion` as a `Color`.

This change would mean more code in `types.rs`, but I think the combination of `setter(into)` for builder methods and `From<(f32...)>` should avoid much verbosity in the consuming code. This would also allow the creation of new inherent methods, such as `Scale::uniform(val: f32) -> Scale`.

**Comment by shockham** [comment]
Yeah, I think there might be a lot of benefit to changing them to a Newtype pattern rather than type alias, so might look into to converting them.

This is a note to myself, but also might be worth converting to using the appropriate types from the [cgmath](https://crates.io/crates/cgmath) crate as they already have a lot of the handy methods implemented.
